### ISSUE TITLE
Improve UI

### ISSUE THREAD

**Issue by ayush-raj13** [ayush-raj13/random-animal-generator#1]

**Comment by GeorgeET15** [comment]
Hi can I work on this, can you assign this issue to me

**Comment by anubhav1206** [comment]
Can I also work on this?

**Comment by ayush-raj13** [comment]
Try to make it responsive

**Comment by anubhav1206** [comment]
> Try to make it responsive

It is already responsive for small and medium screen sizes

**Comment by ayush-raj13** [comment]
Ok, then work on improving ui

**Comment by TheShiveshNetwork** [comment]
@ayush-raj13 assign this to me, I have improved the UI and want to submit a new PR.

**Comment by TheShiveshNetwork** [comment]
@ayush-raj13 also there is a issue with your tailwind dark mode configuration that's why its not working correctly, I have already fixed the issue.
