### ISSUE TITLE
Adding Dark/Light mode

### ISSUE THREAD

**Issue by ayush-raj13** [ayush-raj13/random-animal-generator#2]

**Comment by IrfanSalim** [comment]
I would like to work on this, please assign

**Comment by GeorgeET15** [comment]
Hi can I work on this, can you assign this issue to me.

**Comment by ayush-raj13** [comment]
One person is already assigned to it, you may choose any other issues or create an issue if you wish to work on it

**Comment by GeorgeET15** [comment]
Okay, Thank you...

**Comment by ayush-raj13** [comment]
Fixed in PR #9
